### PR TITLE
add <noscript> info

### PR DESCRIPTION
**Pull request by jedie**

### CODE REVIEW

**Comment by rfk** [comment]
@jedie thanks! Please add yourself to CONTRIBUTORS.txt as well.

**Comment by rfk** [comment]
n/m I see you added yourself already in #96

**Comment by jedie** [comment]
to late ;) https://github.com/jedie/pypyjs/commit/aa10d40913e2de54bd825c58af6093b40cf0b154

**Comment by rfk** [comment]
heh :-)

**Pull request merged**
