### PR TITLE
module_bundler.py: Add more flags to init

### PR DESCRIPTION
**Pull request by ArrestedDevelopment**
This adds the following flags to `module_bundler.py init`:

    --root             change the root directory of the modules
    --modroot          add another module directory to bundle

Example usage:

To bundle a custom `deps` folder and a `site-packages` folder that resides in it, run this command:

    python module_bundler.py init ./lib/modules --root=../deps/pypy --modroot=site-packages

### CODE REVIEW

**Comment by rfk** [comment]
So IIUC, this *replaces* the default stlib modules from the pypy distribution, is that correct?  I'd love to hear more about your use-case here.  Would doing a normal `init` and then using `add` on the customs dependencies also work?

**Comment by ArrestedDevelopment** [comment]
This was mainly so I could include module_bundler.py in a folder with my project that uses pypy.js, and have the pypy.js deps folder be elsewhere on my system

**Comment by rfk** [comment]
I think the custom-pypy-root part makes sense, I split that out to a separate PR in #44 with a slightly tweaked option name.

The `--modroot` part, sounds like it should be served ok by separate use of the `add` command rather than done as part of `init`, but I'm happy to add something extra if there's a use-case that `add` doesn't cover well.

**Comment by rfk** [comment]
Closing this out in favour of #44

**Pull request closed without merging**
