### PR TITLE
add website/editor.html with CodeMirror

### PR DESCRIPTION
**Pull request by jedie**
I started a editor page, see: https://github.com/rfk/pypyjs/issues/100

Looks like this:
screenshot

I use CodeMirror: CodeMirror by Marijn Haverbeke, Distributed under an MIT license
https://github.com/codemirror/codemirror

EDIT: Update the screenshot ;)

### CODE REVIEW

**Comment by jedie** [comment]
currently not working because of: https://github.com/rfk/pypyjs/issues/104

**Comment by jedie** [comment]
Now i added selenium tests for the editor here, too.

I can now merge this with https://github.com/rfk/pypyjs/pull/96 and create a merged pull request.
Should i?

**Comment by rfk** [comment]
> I can now merge this with #96 and create a merged pull request.

Smaller pull-requests are usually better IMHO, I suggest leaving them separate.

**Comment by jedie** [comment]
With https://github.com/jedie/pypyjs/commit/847c34d07a22cf1a4dcb913bcfcffed97fa3c7a3 i have add a work-a-round for https://github.com/rfk/pypyjs/issues/109 ;)

**Comment by jedie** [comment]
current version can be tryout here: https://jedie.github.io/pypyjs/editor.html

**Comment by jedie** [comment]
squashed pull request here: https://github.com/rfk/pypyjs/issues/130

**Pull request closed without merging**
