### PR TITLE
Adds remove as an option to module_bundler->purge

### PR DESCRIPTION
**Pull request by perkinslr**
Adds --remove to purge command.  If the module is preloaded, it completely removes it (removes module content from index.json, and removes import tree entry).  If the module is not preloaded, it removes it from the import tree, but does not touch the underlying file inside the module cache (that file can then be removed via rm).  If the entry points to a directory, only the top level entry is removed, each sub-entry can be removed by a separate entry.  

Probably should support some form of wild-carding, but I'm not sure exactly what form that should be... (simple bash-like? automatically assume all sub modules should be removed? full-on re.match based matching?)

### CODE REVIEW

**Comment by rfk** [comment]
Thanks for diving into this.  From an API point of view, I think this functionality makes more sense as a separate `remove` command than as an option on `preload`, particularly if it's also removing things from the module index and not just the preload list.

> but does not touch the underlying file inside the module cache

I can see the logic in not wanting to remove files, but I wonder if this behaviour would be surprising to users.  It's likely not obvious that there's further cleanup required to remove the file from distribution.

**Comment by perkinslr** [comment]
I thought about doing it as a separate sub-command; it started just as a way to un-preload modules, but doing so without removing them from the index leads to a broken state.  I didn't want to do the work to convert it to a sub command without discussing if that was really the best way to do it, I'll see about moving it to a sub command tomorrow.  

If the only copy of some file a user has is inside the cache, removing it could cause them issues.  I figured I would add a --purge option to actually delete the files out of the cache, and print a warning if the files are de-listed but not removed (as well as list the files that --purge would remove).

**Comment by rfk** [comment]
> Is there a way to modify the files in the pull-request on the fly? Or should I close and reopen it?

Sorry, I didn't catch your edit here.  Yes, if you push more commits on to the branch then it should update the pull-request to match.  Depending on how comfortable you are with git, you can also "rebase and force-push" to replace the existing commits with new ones.

**Comment by perkinslr** [comment]
Okay, I think that should do it.  I still don't have it delete files automatically unless --purge is included.  Also, it uses python's re to determine matches, that was the simplest way to handle getting entire packages.

**Comment by rfk** [comment]
great, thanks for this

**Pull request merged**
